services:
  - type: web
    name: trader-socket-server
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 3000
      - key: MAIN_APP_URL
        sync: false
      - key: CMS_URL
        sync: false

